### ISSUE TITLE
Directory listing formatting improvements

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/drupal-module-directory#3]
We need to order the departments in a sensible way, format the name/job title area.

https://github.com/City-of-Bloomington/drupal-theme-cob/issues/101

**Comment by inghamn** [comment]
Sorted the departments alphabetically
dd664387d72f3190179475da35a223b391381a58

**Comment by rbdietz** [comment]
Also provide table of contents for navigation

format name/job title area so they don't run together.
