### ISSUE TITLE
AD access model

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/drupal-module-directory#6]
Drop restricted flag.  Add "public" flag.  Retain "promoted" flag.  Do this to prevent personnel who should be restricted from being published by default.

**Comment by rbdietz** [comment]
Here are some possible flags for discussion...

public - visible in /directory only to internal staff
published - visible in /directory to internal staff and external users
promoted - highlighted on department web pages
[none]: not visible in /directory at all

open to other options.

**Comment by inghamn** [comment]
Moved to the redmine issue tracker for Directory
